# Generated by Django 5.0.3 on 2024-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_thali',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='thali_tag_line',
            field=models.CharField(default='', max_length=200),
        ),
    ]
