# Generated by Django 5.0.3 on 2024-04-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_dish_is_thali_dish_thali_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='thali_items',
            field=models.TextField(default=''),
        ),
    ]
